### PR TITLE
Log a message every minute while sending results to Report Portal

### PR DESCRIPTION
**Pull request by matt-richardson**
We use the `----blame-hang-timeout` flag to `dotnet test` so that we can get a process dump when a test hangs.
We were setting this to `5m`, but found that occasionally the publishing would take more than this time to send all the test results / log messages to the server.

When report portal took too long, the "hang detection" process would kill the test run.

This PR adds a log message every minute while waiting for all logs / test results to finish sending.

Note: I haven't been able to test this locally 😢. I did try, honest.

### CODE REVIEW

**Comment by nvborisenko** [comment]
Thanks for the idea. Related to https://github.com/reportportal/client-dotnet/issues/133 Let's keep this PR open until related functionality is implemented in common library. Thanks for understanding.

**Comment by nvborisenko** [comment]
Or we can release this functionality as is, based on how critical it is for you. @matt-richardson ?

**Comment by matt-richardson** [comment]
> Or we can release this functionality as is, based on how critical it is for you. @matt-richardson ?

I'd vote to have this go in, even if it gets reverted when https://github.com/reportportal/client-dotnet/issues/133 gets implemented. 

At the moment, we've had to disable the blame-hang functionality, which means we lose diagnostics ability.

Given (I'm told that) 135 is blocked by some other refactoring, an interim solution like this would help us have the best of both worlds.

**Comment by matt-richardson** [comment]
Hey @nvborisenko - is merging / releasing this possible? 
This will unblock some work on our side. Thanks in advance!

**Comment by nvborisenko** [comment]
I don't mind releasing a patch for you. Before doing it let's fix build error :)

**Comment by matt-richardson** [comment]
Oops - didn't notice that. Will fix now.

**Comment by matt-richardson** [comment]
Okay, fixed 👍. Sorry about that.

**Comment by nvborisenko** [comment]
Done in v2.4.3 thanks, Matt, for your contribution.

**Pull request merged**
